# -*- coding: utf-8 -*-

# Learn more: https://github.com/kennethreitz/setup.py

from setuptools import setup

setup(
    name='qrev',
    version='4.41.2',
    description='QRev port to python',
    author='David S. Mueller',
    author_email='dmueller@usgs.gov',
    url="https://code.usgs.gov/QRev/QRevPy",
    license="CC0 1.0",
    REQUIRES_PYTHON='>=3.13.11',
    packages= ['qrev', 'qrev.Classes', 'qrev.DischargeFunctions',
              'qrev.MiscLibs', 'qrev.UI', 'qrev.translation',
              'qrev_docs'],
    package_data= {'qrev_docs': ['source/*',
                                  'source/assets/files/*',
                                 'source/assets/user_guide/*',
                                 'source/assets/tech_manual/*',
                                  'index.rst',
                                  'make.bat',
                                  'Makefile',
                                  ],
                   'qrev.translation': ['*.qm']},
    include_package_data=True,
    install_requires=['PyQt5',
                      'PyQt5-sip',
                      'PyQt5-stubs',
                      'altgraph',
                      'atomicwrites~=1.4.1',
                      'attrs~=25.2.0',
                      'click>=7.1.2',
                      'colorama',
                      'cycler==0.10.0',
                      'future~=0.17.1',
                      'importlib-metadata',
                      'macholib==1.11',
                      'matplotlib==3.8.0',
                      'more-itertools==10.1.0',
                      'statsmodels~=0.14.6',
                      'numpy==1.26.2',
                      'numba~=0.61.0',
                      'pandas==2.2.0',
                      'pefile',
                      'py~=1.11.0',
                      'pyparsing==3.1.1',
                      'python-dateutil',
                      'python-dotenv~=1.0.1',
                      'pytz',
                      'pywin32-ctypes',
                      'reportlab',
                      'scipy==1.14.1',
                      'sigfig==1.3.3',
                      'simplekml',
                      'sip',
                      'six==1.17.0',
                      'utm',
                      'wcwidth==0.1.7',
                      'xmltodict==0.13.0',
                      'zipp==3.17.0',
                      'sphinx-markdown-builder',
                      'sphinx',
                      'myst-parser',
                      'sphinx_book_theme'
                      ],)
