# -*- coding: utf-8 -*-

# Learn more: https://github.com/kennethreitz/setup.py

from setuptools import setup

setup(
    name='qrev',
    version='4.40.1',
    description='QRev port to python',
    author='David S. Mueller',
    author_email='dmueller@usgs.gov',
    url="https://code.usgs.gov/QRev/QRevPy",
    license="CC0 1.0",
    REQUIRES_PYTHON='>=3.11.9',
    packages= ['qrev', 'qrev.Classes', 'qrev.DischargeFunctions',
              'qrev.MiscLibs', 'qrev.UI', 'qrev.translation',
              'qrev_docs'],
    package_data= {'qrev_docs': ['source/*',
                                  'source/assets/files/*',
                                 'source/assets/user_guide/*',
                                 'source/assets/tech_manual/*',
                                  'index.rst',
                                  'make.bat',
                                  'Makefile',
                                  ],
                   'qrev.translation': ['*.qm']},
    include_package_data=True,
    install_requires=['PyInstaller==6.15.0',
                      'pyinstaller-hooks-contrib',
                      'pyinstaller-versionfile',
                      'PyQt5',
                      'PyQt5-sip',
                      'PyQt5-stubs',
                      'altgraph==0.16.1',
                      'atomicwrites==1.3.0',
                      'attrs==19.1.0',
                      'click>=7.1.2',
                      'colorama==0.4.1',
                      'cycler==0.10.0',
                      'future==0.17.1',
                      'importlib-metadata',
                      'macholib==1.11',
                      'matplotlib==3.6.3',
                      'more-itertools==7.2.0',
                      'statsmodels~=0.13.5',
                      'numpy==1.26.2',
                      'numba~=0.61.0',
                      'pandas==1.4.0',
                      'pefile',
                      'py==1.8.0',
                      'pyparsing==2.4.2',
                      'python-dateutil',
                      'python-dotenv==0.10.3',
                      'pytz',
                      'pywin32-ctypes',
                      'reportlab',
                      'scipy==1.10.0',
                      'scikit-learn==1.3.2',
                      'sigfig==1.3.3',
                      'simplekml',
                      'sip',
                      'six==1.12.0',
                      'utm',
                      'wcwidth==0.1.7',
                      'xmltodict==0.12.0',
                      'zipp==0.6.0',
                      'sphinx-markdown-builder',
                      'sphinx',
                      'myst-parser',
                      'sphinx_book_theme'
                      ],)
