# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Axes_Scale.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets
from qrev.UI import Axes_Scale


class AxesScale(QtWidgets.QDialog, Axes_Scale.Ui_Axes_Scale):
    """Dialog to allow users to change heading offset.

    Parameters
    ----------
    Axes_Scale.Ui_Axes_Scale : QDialog
        Dialog window to allow users to change axes scaline
    """

    def __init__(self, parent=None):
        super(AxesScale, self).__init__(parent)
        self.setupUi(self)