from PyQt5 import QtWidgets, QtCore
from qrev.UI import wTransects2Use
from qrev.MiscLibs.local_time_utilities import tz_formatted_string


class Transects2Use(QtWidgets.QDialog, wTransects2Use.Ui_Transects2Use):
    """Dialog to allow users to select and deselect transects to use in the
    discharge computation.

    Parameters
    ----------
    wTransects2Use.Ui_Transects2Use : QDialog
        Dialog window with options for users
    """

    def __init__(self, parent=None):
        """Initialize dialog

        Parameters
        ----------
        parent: QRev
            Main UI
        """

        super(Transects2Use, self).__init__(parent)
        self.setupUi(self)
        self.parent = parent

        # Populate table
        self.summary_table()

        # Setup connections for buttons
        self.pb_check_all.clicked.connect(self.check_all)
        self.pb_uncheck_all.clicked.connect(self.uncheck_all)

    def keyPressEvent(self, e):
        """Implements shortcut keys.

        Parameters
        ----------
        e: event
            Generated by key pressed by user
        """
        # maximize window
        if e.key() == QtCore.Qt.Key_M:
            self.showMaximized()

    def check_all(self):
        """Checks all transects for use."""

        for transect in self.parent.meas.transects:
            transect.checked = True
        self.summary_table()

    def uncheck_all(self):
        """Unchecks all transects for user."""

        for transect in self.parent.meas.transects:
            transect.checked = False
        self.summary_table()

    def summary_table(self):
        """Create and populate main summary table."""

        parent = self.parent
        tbl = self.tableSelect
        units = parent.units

        # Initialize table headers
        summary_header = [
            parent.tr("Select Transect"),
            parent.tr("Start"),
            parent.tr("Bank"),
            parent.tr("End"),
            parent.tr("Duration"),
            parent.tr("Total Q"),
            parent.tr("Top Q"),
            parent.tr("Meas Q"),
            parent.tr("Bottom Q"),
            parent.tr("Left Q"),
            parent.tr("Right Q"),
        ]

        # Setup table
        ncols = len(summary_header)
        nrows = len(parent.meas.transects)
        tbl.setRowCount(nrows)
        tbl.setColumnCount(ncols)
        tbl.setHorizontalHeaderLabels(summary_header)
        tbl.horizontalHeader().setFont(parent.font_bold)
        tbl.verticalHeader().hide()
        tbl.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)

        # Add transect data
        for row in range(nrows):
            col = 0
            transect_id = row
            checked = QtWidgets.QTableWidgetItem(
                parent.meas.transects[transect_id].file_name[:-4]
            )
            checked.setFlags(QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
            if parent.meas.transects[row].checked:
                checked.setCheckState(QtCore.Qt.Checked)
            else:
                checked.setCheckState(QtCore.Qt.Unchecked)
            checked.setFlags(QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
            tbl.setItem(row, col, checked)

            col += 1
            tbl.setItem(
                row,
                col,
                QtWidgets.QTableWidgetItem(tz_formatted_string(
                    parent.meas.transects[
                        transect_id
                    ].date_time.start_serial_time,
                    parent.meas.transects[
                        transect_id
                    ].date_time.utc_time_offset,
                    "%H:%M:%S")
                ),
            )
            tbl.item(row, col).setFlags(QtCore.Qt.ItemIsEnabled)

            col += 1
            tbl.setItem(
                row,
                col,
                QtWidgets.QTableWidgetItem(
                    parent.meas.transects[transect_id].start_edge[0]
                ),
            )
            tbl.item(row, col).setFlags(QtCore.Qt.ItemIsEnabled)

            col += 1
            tbl.setItem(
                row,
                col,
                QtWidgets.QTableWidgetItem(tz_formatted_string(
                    parent.meas.transects[
                        transect_id
                    ].date_time.end_serial_time,
                    parent.meas.transects[
                        transect_id
                    ].date_time.utc_time_offset,
                    "%H:%M:%S")
                ),
            )
            tbl.item(row, col).setFlags(QtCore.Qt.ItemIsEnabled)

            col += 1
            tbl.setItem(
                row,
                col,
                QtWidgets.QTableWidgetItem(
                    "{:5.1f}".format(
                        parent.meas.transects[
                            transect_id
                        ].date_time.transect_duration_sec
                    )
                ),
            )
            tbl.item(row, col).setFlags(QtCore.Qt.ItemIsEnabled)

            col += 1
            tbl.setItem(
                row,
                col,
                QtWidgets.QTableWidgetItem(
                    "{:8.2f}".format(
                        parent.meas.discharge[transect_id].total * units["Q"]
                    )
                ),
            )
            tbl.item(row, col).setFlags(QtCore.Qt.ItemIsEnabled)

            col += 1
            tbl.setItem(
                row,
                col,
                QtWidgets.QTableWidgetItem(
                    "{:7.2f}".format(
                        parent.meas.discharge[transect_id].top * units["Q"]
                    )
                ),
            )
            tbl.item(row, col).setFlags(QtCore.Qt.ItemIsEnabled)

            col += 1
            tbl.setItem(
                row,
                col,
                QtWidgets.QTableWidgetItem(
                    "{:7.2f}".format(
                        parent.meas.discharge[transect_id].middle * units["Q"]
                    )
                ),
            )
            tbl.item(row, col).setFlags(QtCore.Qt.ItemIsEnabled)

            col += 1
            tbl.setItem(
                row,
                col,
                QtWidgets.QTableWidgetItem(
                    "{:7.2f}".format(
                        parent.meas.discharge[transect_id].bottom * units["Q"]
                    )
                ),
            )
            tbl.item(row, col).setFlags(QtCore.Qt.ItemIsEnabled)

            col += 1
            tbl.setItem(
                row,
                col,
                QtWidgets.QTableWidgetItem(
                    "{:7.2f}".format(
                        parent.meas.discharge[transect_id].left * units["Q"]
                    )
                ),
            )
            tbl.item(row, col).setFlags(QtCore.Qt.ItemIsEnabled)

            col += 1
            tbl.setItem(
                row,
                col,
                QtWidgets.QTableWidgetItem(
                    "{:7.2f}".format(
                        parent.meas.discharge[transect_id].right * units["Q"]
                    )
                ),
            )
            tbl.item(row, col).setFlags(QtCore.Qt.ItemIsEnabled)

        tbl.resizeColumnsToContents()
        tbl.resizeRowsToContents()
