# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wOptions.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Options(object):
    def setupUi(self, Options):
        Options.setObjectName("Options")
        Options.resize(845, 303)
        self.gridLayout_2 = QtWidgets.QGridLayout(Options)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.QGroupBox = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.QGroupBox.setFont(font)
        self.QGroupBox.setObjectName("QGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.QGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cb_weighted_extrap = QtWidgets.QCheckBox(self.QGroupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb_weighted_extrap.setFont(font)
        self.cb_weighted_extrap.setObjectName("cb_weighted_extrap")
        self.verticalLayout_2.addWidget(self.cb_weighted_extrap)
        self.gridLayout.addWidget(self.QGroupBox, 0, 2, 1, 1)
        self.gb_units = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_units.setFont(font)
        self.gb_units.setObjectName("gb_units")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gb_units)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rb_english = QtWidgets.QRadioButton(self.gb_units)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_english.setFont(font)
        self.rb_english.setChecked(True)
        self.rb_english.setObjectName("rb_english")
        self.verticalLayout_3.addWidget(self.rb_english)
        self.rb_si = QtWidgets.QRadioButton(self.gb_units)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rb_si.setFont(font)
        self.rb_si.setObjectName("rb_si")
        self.verticalLayout_3.addWidget(self.rb_si)
        self.gridLayout.addWidget(self.gb_units, 0, 0, 1, 1)
        self.gb_color_map = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_color_map.setFont(font)
        self.gb_color_map.setObjectName("gb_color_map")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.gb_color_map)
        self.verticalLayout_7.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rb_viridis = QtWidgets.QRadioButton(self.gb_color_map)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_viridis.setFont(font)
        self.rb_viridis.setChecked(True)
        self.rb_viridis.setObjectName("rb_viridis")
        self.verticalLayout_7.addWidget(self.rb_viridis)
        self.rb_jet = QtWidgets.QRadioButton(self.gb_color_map)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_jet.setFont(font)
        self.rb_jet.setObjectName("rb_jet")
        self.verticalLayout_7.addWidget(self.rb_jet)
        self.gridLayout.addWidget(self.gb_color_map, 1, 0, 1, 1)
        self.gb_uncertainty = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_uncertainty.setFont(font)
        self.gb_uncertainty.setObjectName("gb_uncertainty")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gb_uncertainty)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rb_qrev_u = QtWidgets.QRadioButton(self.gb_uncertainty)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_qrev_u.setFont(font)
        self.rb_qrev_u.setChecked(True)
        self.rb_qrev_u.setObjectName("rb_qrev_u")
        self.verticalLayout_4.addWidget(self.rb_qrev_u)
        self.rb_oursin_u = QtWidgets.QRadioButton(self.gb_uncertainty)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_oursin_u.setFont(font)
        self.rb_oursin_u.setObjectName("rb_oursin_u")
        self.verticalLayout_4.addWidget(self.rb_oursin_u)
        self.gridLayout.addWidget(self.gb_uncertainty, 1, 2, 1, 1)
        self.gb_save_options = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_save_options.setFont(font)
        self.gb_save_options.setObjectName("gb_save_options")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gb_save_options)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_All = QtWidgets.QRadioButton(self.gb_save_options)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rb_All.setFont(font)
        self.rb_All.setChecked(True)
        self.rb_All.setObjectName("rb_All")
        self.verticalLayout.addWidget(self.rb_All)
        self.rb_checked = QtWidgets.QRadioButton(self.gb_save_options)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rb_checked.setFont(font)
        self.rb_checked.setObjectName("rb_checked")
        self.verticalLayout.addWidget(self.rb_checked)
        self.line = QtWidgets.QFrame(self.gb_save_options)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.cb_rating = QtWidgets.QCheckBox(self.gb_save_options)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb_rating.setFont(font)
        self.cb_rating.setObjectName("cb_rating")
        self.verticalLayout.addWidget(self.cb_rating)
        self.line_2 = QtWidgets.QFrame(self.gb_save_options)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.cb_stylesheet = QtWidgets.QCheckBox(self.gb_save_options)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb_stylesheet.setFont(font)
        self.cb_stylesheet.setObjectName("cb_stylesheet")
        self.verticalLayout.addWidget(self.cb_stylesheet)
        self.line_3 = QtWidgets.QFrame(self.gb_save_options)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.cb_xs_export = QtWidgets.QCheckBox(self.gb_save_options)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cb_xs_export.setFont(font)
        self.cb_xs_export.setChecked(True)
        self.cb_xs_export.setObjectName("cb_xs_export")
        self.verticalLayout.addWidget(self.cb_xs_export)
        self.gridLayout.addWidget(self.gb_save_options, 0, 1, 2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Options)
        self.buttonBox.accepted.connect(Options.accept)
        self.buttonBox.rejected.connect(Options.reject)
        QtCore.QMetaObject.connectSlotsByName(Options)

    def retranslateUi(self, Options):
        _translate = QtCore.QCoreApplication.translate
        Options.setWindowTitle(_translate("Options", "Dialog"))
        self.QGroupBox.setTitle(_translate("Options", "Extrapolation"))
        self.cb_weighted_extrap.setText(_translate("Options", "Discharge weighted"))
        self.gb_units.setTitle(_translate("Options", "Units"))
        self.rb_english.setText(_translate("Options", "English"))
        self.rb_si.setText(_translate("Options", "SI"))
        self.gb_color_map.setTitle(_translate("Options", "Color Map"))
        self.rb_viridis.setText(_translate("Options", "viridis"))
        self.rb_jet.setText(_translate("Options", "jet"))
        self.gb_uncertainty.setTitle(_translate("Options", "Uncertainty"))
        self.rb_qrev_u.setText(_translate("Options", "QRev Original"))
        self.rb_oursin_u.setText(_translate("Options", "Oursin"))
        self.gb_save_options.setTitle(_translate("Options", "Save Options"))
        self.rb_All.setText(_translate("Options", "All Transects"))
        self.rb_checked.setText(_translate("Options", "Only Checked Transects"))
        self.cb_rating.setText(_translate("Options", "Prompt for rating on save"))
        self.cb_stylesheet.setText(_translate("Options", "Save style sheet with data"))
        self.cb_xs_export.setText(_translate("Options", "Export Mean Cross-Section"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Options = QtWidgets.QDialog()
    ui = Ui_Options()
    ui.setupUi(Options)
    Options.show()
    sys.exit(app.exec_())
