# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wOptions.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Options(object):
    def setupUi(self, Options):
        Options.setObjectName("Options")
        Options.resize(351, 844)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(Options)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gb_units = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_units.setFont(font)
        self.gb_units.setObjectName("gb_units")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.gb_units)
        self.verticalLayout_8.setContentsMargins(-1, 5, 11, 5)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.rb_english = QtWidgets.QRadioButton(self.gb_units)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_english.setFont(font)
        self.rb_english.setChecked(True)
        self.rb_english.setObjectName("rb_english")
        self.verticalLayout_8.addWidget(self.rb_english)
        self.rb_si = QtWidgets.QRadioButton(self.gb_units)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_si.setFont(font)
        self.rb_si.setObjectName("rb_si")
        self.verticalLayout_8.addWidget(self.rb_si)
        self.verticalLayout_3.addWidget(self.gb_units)
        self.gb_axis = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_axis.setFont(font)
        self.gb_axis.setObjectName("gb_axis")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gb_axis)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rb_opt_ensembles = QtWidgets.QRadioButton(self.gb_axis)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rb_opt_ensembles.setFont(font)
        self.rb_opt_ensembles.setChecked(True)
        self.rb_opt_ensembles.setObjectName("rb_opt_ensembles")
        self.verticalLayout_2.addWidget(self.rb_opt_ensembles)
        self.rb_opt_length = QtWidgets.QRadioButton(self.gb_axis)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rb_opt_length.setFont(font)
        self.rb_opt_length.setObjectName("rb_opt_length")
        self.verticalLayout_2.addWidget(self.rb_opt_length)
        self.rb_opt_time = QtWidgets.QRadioButton(self.gb_axis)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rb_opt_time.setFont(font)
        self.rb_opt_time.setObjectName("rb_opt_time")
        self.verticalLayout_2.addWidget(self.rb_opt_time)
        self.verticalLayout_3.addWidget(self.gb_axis)
        self.gb_color_map = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_color_map.setFont(font)
        self.gb_color_map.setObjectName("gb_color_map")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.gb_color_map)
        self.verticalLayout_7.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rb_viridis = QtWidgets.QRadioButton(self.gb_color_map)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_viridis.setFont(font)
        self.rb_viridis.setChecked(True)
        self.rb_viridis.setObjectName("rb_viridis")
        self.verticalLayout_7.addWidget(self.rb_viridis)
        self.rb_jet = QtWidgets.QRadioButton(self.gb_color_map)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_jet.setFont(font)
        self.rb_jet.setObjectName("rb_jet")
        self.verticalLayout_7.addWidget(self.rb_jet)
        self.verticalLayout_3.addWidget(self.gb_color_map)
        self.gb_save_options = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_save_options.setFont(font)
        self.gb_save_options.setObjectName("gb_save_options")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gb_save_options)
        self.verticalLayout.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_All = QtWidgets.QRadioButton(self.gb_save_options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_All.setFont(font)
        self.rb_All.setChecked(True)
        self.rb_All.setObjectName("rb_All")
        self.verticalLayout.addWidget(self.rb_All)
        self.rb_checked = QtWidgets.QRadioButton(self.gb_save_options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_checked.setFont(font)
        self.rb_checked.setObjectName("rb_checked")
        self.verticalLayout.addWidget(self.rb_checked)
        self.line = QtWidgets.QFrame(self.gb_save_options)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.cb_rating = QtWidgets.QCheckBox(self.gb_save_options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cb_rating.setFont(font)
        self.cb_rating.setObjectName("cb_rating")
        self.verticalLayout.addWidget(self.cb_rating)
        self.line_2 = QtWidgets.QFrame(self.gb_save_options)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.cb_stylesheet = QtWidgets.QCheckBox(self.gb_save_options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cb_stylesheet.setFont(font)
        self.cb_stylesheet.setObjectName("cb_stylesheet")
        self.verticalLayout.addWidget(self.cb_stylesheet)
        self.verticalLayout_3.addWidget(self.gb_save_options)
        self.gb_extrap_weighted = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_extrap_weighted.setFont(font)
        self.gb_extrap_weighted.setObjectName("gb_extrap_weighted")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gb_extrap_weighted)
        self.verticalLayout_6.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cb_weighted_extrap = QtWidgets.QCheckBox(self.gb_extrap_weighted)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cb_weighted_extrap.setFont(font)
        self.cb_weighted_extrap.setObjectName("cb_weighted_extrap")
        self.verticalLayout_6.addWidget(self.cb_weighted_extrap)
        self.verticalLayout_3.addWidget(self.gb_extrap_weighted)
        self.gb_filters = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_filters.setFont(font)
        self.gb_filters.setObjectName("gb_filters")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gb_filters)
        self.verticalLayout_5.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.rb_filter_transect = QtWidgets.QRadioButton(self.gb_filters)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_filter_transect.setFont(font)
        self.rb_filter_transect.setChecked(True)
        self.rb_filter_transect.setObjectName("rb_filter_transect")
        self.verticalLayout_5.addWidget(self.rb_filter_transect)
        self.rb_filter_meas = QtWidgets.QRadioButton(self.gb_filters)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_filter_meas.setFont(font)
        self.rb_filter_meas.setObjectName("rb_filter_meas")
        self.verticalLayout_5.addWidget(self.rb_filter_meas)
        self.verticalLayout_3.addWidget(self.gb_filters)
        self.gb_uncertainty = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_uncertainty.setFont(font)
        self.gb_uncertainty.setObjectName("gb_uncertainty")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gb_uncertainty)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rb_qrev_u = QtWidgets.QRadioButton(self.gb_uncertainty)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_qrev_u.setFont(font)
        self.rb_qrev_u.setChecked(True)
        self.rb_qrev_u.setObjectName("rb_qrev_u")
        self.verticalLayout_4.addWidget(self.rb_qrev_u)
        self.rb_oursin_u = QtWidgets.QRadioButton(self.gb_uncertainty)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.rb_oursin_u.setFont(font)
        self.rb_oursin_u.setObjectName("rb_oursin_u")
        self.verticalLayout_4.addWidget(self.rb_oursin_u)
        self.verticalLayout_3.addWidget(self.gb_uncertainty)
        self.gb_moving_bed_option = QtWidgets.QGroupBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gb_moving_bed_option.setFont(font)
        self.gb_moving_bed_option.setObjectName("gb_moving_bed_option")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.gb_moving_bed_option)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.cb_allow_manual_no_mb = QtWidgets.QCheckBox(self.gb_moving_bed_option)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cb_allow_manual_no_mb.setFont(font)
        self.cb_allow_manual_no_mb.setObjectName("cb_allow_manual_no_mb")
        self.verticalLayout_9.addWidget(self.cb_allow_manual_no_mb)
        self.verticalLayout_3.addWidget(self.gb_moving_bed_option)
        self.verticalLayout_10.addLayout(self.verticalLayout_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Options)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_10.addWidget(self.buttonBox)

        self.retranslateUi(Options)
        self.buttonBox.accepted.connect(Options.accept)
        self.buttonBox.rejected.connect(Options.reject)
        QtCore.QMetaObject.connectSlotsByName(Options)

    def retranslateUi(self, Options):
        _translate = QtCore.QCoreApplication.translate
        Options.setWindowTitle(_translate("Options", "Dialog"))
        self.gb_units.setTitle(_translate("Options", "Units"))
        self.rb_english.setText(_translate("Options", "English"))
        self.rb_si.setText(_translate("Options", "SI"))
        self.gb_axis.setTitle(_translate("Options", "Default X-Axis"))
        self.rb_opt_ensembles.setText(_translate("Options", "Ensembles"))
        self.rb_opt_length.setText(_translate("Options", "Length"))
        self.rb_opt_time.setText(_translate("Options", "Time"))
        self.gb_color_map.setTitle(_translate("Options", "Color Map"))
        self.rb_viridis.setText(_translate("Options", "viridis"))
        self.rb_jet.setText(_translate("Options", "jet"))
        self.gb_save_options.setTitle(_translate("Options", "Save Options"))
        self.rb_All.setText(_translate("Options", "All Transects"))
        self.rb_checked.setText(_translate("Options", "Only Checked Transects"))
        self.cb_rating.setText(_translate("Options", "Prompt for rating on save"))
        self.cb_stylesheet.setText(_translate("Options", "Save style sheet with data"))
        self.gb_extrap_weighted.setTitle(_translate("Options", "Extrapolation"))
        self.cb_weighted_extrap.setText(_translate("Options", "Discharge weighted"))
        self.gb_filters.setTitle(_translate("Options", "WT, BT Filters"))
        self.rb_filter_transect.setText(_translate("Options", "By Transect"))
        self.rb_filter_meas.setText(_translate("Options", "By Measurement"))
        self.gb_uncertainty.setTitle(_translate("Options", "Uncertainty"))
        self.rb_qrev_u.setText(_translate("Options", "QRev Original"))
        self.rb_oursin_u.setText(_translate("Options", "Oursin"))
        self.gb_moving_bed_option.setTitle(_translate("Options", "Moving Bed"))
        self.cb_allow_manual_no_mb.setText(_translate("Options", "Allow observed no moving-bed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Options = QtWidgets.QDialog()
    ui = Ui_Options()
    ui.setupUi(Options)
    Options.show()
    sys.exit(app.exec_())
